// User action types
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS'
export const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_SET_CURRENT_USER = 'USER_SET_CURRENT_USER'
export const USER_SET_TV_SERIES_WISHLIST = 'USER_SET_TV_SERIES_WISHLIST'
export const USER_SET_MOVIES_WISHLIST = 'USER_SET_MOVIES_WISHLIST'

// Movie action types
export const MOVIES_GET_DETAILS_SUCCESS = 'MOVIES_GET_DETAILS_SUCCESS'
export const MOVIES_GET_CAST_SUCCESS = 'MOVIES_GET_CAST_SUCCESS'
export const MOVIES_SEARCH_SUCCESS = 'MOVIES_SEARCH_SUCCESS'
export const MOVIES_SEARCH_CLEAR = 'MOVIES_SEARCH_CLEAR'
export const MOVIES_DETAILS_CLEAR = 'MOVIES_DETAILS_CLEAR'

// TV Series action types
export const TVSERIES_GET_DETAILS_SUCCESS = 'TVSERIES_GET_DETAILS_SUCCESS'
export const TVSERIES_GET_CAST_SUCCESS = 'TVSERIES_GET_CAST_SUCCESS'
export const TVSERIES_SEARCH_SUCCESS = 'TVSERIES_SEARCH_SUCCESS'
export const TVSERIES_SEARCH_CLEAR = 'TVSERIES_SEARCH_CLEAR'
export const TVSERIES_DETAILS_CLEAR = 'TVSERIES_DETAILS_CLEAR'

// App action types
export const APP_MEDIA_SEARCH_SUCCESS = 'APP_MEDIA_SEARCH_SUCCESS'
export const APP_MEDIA_SEARCH_CLEAR = 'APP_MEDIA_SEARCH_CLEAR'
